### ISSUE TITLE
integrate_subwords_tags()のエラー(list index out of range)

### ISSUE THREAD

**Issue by shuntaroy** [sociocom/MedNER-J#2]
サンプルより長めの文章で `predict()` が失敗します．
`integrate_subwords_tags()` でうまくいっていないようです．
私には細かい挙動がよくわからないので調査お願いします．

## エラー
```
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    results = model.predict(sents, form)
  File "/Users/s-yada/Developments/GitHub/MedEXJ2/ner.py", line 89, in predict
    tags = self.integrate_subwords_tags(tags, lengths[s_idx:e_idx])
  File "/Users/s-yada/Developments/GitHub/MedEXJ2/ner.py", line 66, in integrate_subwords_tags
    tag = merge(ts[idx : idx + l])
  File "/Users/s-yada/Developments/GitHub/MedEXJ2/ner.py", line 58, in merge
    return tags[0]
IndexError: list index out of range
```

## 入力テキスト

これ以外のテキストでも失敗します．
以下は短めのもの．

```
【背景・目的】急性呼吸窮迫症候群（以下、　ＡＲＤＳ）における急性期の腹臥位療法は酸素化の改善に有効とされる。
一方で、本邦では体交時の合併症への懸念、マンパワーの不足により腹臥位療法の実施が困難な場合が多い。
今回、多職種で連携を密にし腹臥位療法を実施した結果、人工呼吸器から離脱できた症例を経験したため報告する。
【方法または症例】症例はインフルエンザ肺炎によるＡＲＤＳと診断され、人工呼吸器管理となった６０代男性である。
既往に間質性肺炎があり、入院時の胸部ＣＴで両側に下葉優位のびまん性スリガラス陰影を認めた。
入院日のカンファレンスで医師、看護師、理学療法士で腹臥位療法の必要性について検討した。
入院２日目に医師、看護師とともに腹臥位療法を開始し入院１４日目まで４時間／回、２回／日の頻度で継続した。
褥瘡予防のため２時間おきに除圧を行った。
腹臥位療法の時間帯、実施前後の全身状態、合併症の有無について適時情報を共有した。
腹臥位以外の時間は両側への完全側臥位を実施した。
```

**Comment by ujiuji1259** [comment]
subwordで消えてしまう文字（スペースなど）で失敗しているようでした．

**Comment by ujiuji1259** [comment]
修正しました．
こちらで動作は確認しましたが，念のため動作確認お願いできますでしょうか

**Comment by shuntaroy** [comment]
動作しました！
