### ISSUE TITLE
AssertionError in convert_iob_to_dict

### ISSUE THREAD

**Issue by shuntaroy** [sociocom/MedNER-J#3]
## エラー
```
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    results = model.predict(sents, form)
  File "/Users/s-yada/Developments/GitHub/MedEXJ2/ner.py", line 134, in predict
    results = convert_iob_to_dict(tokens, results)
  File "/Users/s-yada/Developments/GitHub/MedEXJ2/util.py", line 12, in convert_iob_to_dict
    assert len(tt) == len(ii), ''
AssertionError
```

## 入力
```
【背景】門脈体循環シャントによる肝性脳症は，肝硬変や門脈圧充進症などの背景疾患を認めることが多い．
今回，肝臓に基礎疾患を認めず急性発症した肝性脳症に対して肝内門脈肝静脈シャントと診断し経皮経肝塞栓術　（ｐｅｒｃｕｔａ－ｎｅｏｕｓ　ｔｒａｎｓｈｅｐａｔｉｃ　ｏｂｌｉｔｅｒａｔｉｏｎ　；　ＰＴＯ）を行った症例を経験したので，報告する．
【症例】症例は６８歳，男性．
心筋梗塞での加療中に傾眠傾向を認め，血液検査にて高アンモニア血症（１９３μｇ／ｄＬ）を指摘された．
頭部ＭＲＩのＴ１強調画像にて両側淡蒼球に高信号を認め，肝性脳症による意識障害と診断され，先天性代謝障害などが疑われ当院に紹介受診となった．
飲酒歴なし．
ＨＢｓ抗原陰性，ＨＣＶ抗体陰性．
転院時アンモニア１７６μｇ／ｄＬ，　フィッシャー比１．４（基準２．４３～４．４），血中シトルリン２７．８ｎｍｏｌ／ｍＬ（基準１７．１～４２．６ｎｍｏｌ／ｍＬ）．
腹部エコーにて肝の形態に異常を認めず，左門脈分枝の拡張を認め，ドップラーにて門脈肝静脈シャントを疑った．
造影ＣＴにて肝内シャントのみで肝外にはシャントを認めなかった．
前医から開始していたラクチトールを増量したが効果乏しいため，　ＰＴＯを施行した．
門脈造影では，　ＣＴにて指摘の門脈左枝のシャントの他に，両葉に無数の非拡張性のシャントが認められた．
門脈左枝の瘤化している門脈肝静脈シャントに対して金属コイルにて塞栓を行った．
治療後，アンモニアは直ちに正常値化（４２μｇ／ｄＬ）し，以後も上昇なく経過した．
ラクチトール中止後もアンモニアの上昇を認めなかった．
【考察】本症例は，肝臓の基礎疾患なく突如発症した肝性脳症であるが，腹部エコー，造影ＣＴにて速やかに診断され治療に進むことができた．
肝性脳症の原因としては，肝硬変や門脈圧充進症に伴う門脈体循環シャントによるもの，尿素回路の先天的代謝障害などの他，本症例のように肝疾患を伴わない門脈体循環シャントによるものも報告されており，中でも肝内門脈肝静脈シャントの頻度はまれとされている．
成因として，外傷，肝生検の既往などがある場合は後天性と推測される．
本症例は急性心筋梗塞以外の既往はなく，先天的なものと考えられた．
無症状で偶然診断されたり，高齢になって初めて肝性脳症で診断される報告もあり，非硬変肝症例における肝性脳症の鑑別として念頭に置くべきと考えられた．
【結語】肝内門脈肝静脈シャントによる肝性脳症に対して経皮経肝塞栓術が奏功した．
```

**Comment by ujiuji1259** [comment]
おそらく修正できました
